const C = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  TOGGLE_CART: "TOGGLE_CART",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
};
export default C;
